CREATE DATABASE IF NOT EXISTS ably;
CREATE DATABASE IF NOT EXISTS ably_test;

-- 유저 권한 부여
GRANT ALL PRIVILEGES ON *.* TO 'ably'@'%';
FLUSH PRIVILEGES;

-- 테이블 생성
CREATE TABLE USER_INFO (
	CREATED_AT TIMESTAMP NULL DEFAULT NULL,
	ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(100) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY UNIQUE_EMAIL (EMAIL)
);

CREATE TABLE PRODUCT(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	THUMBNAIL VARCHAR(300) NOT NULL,
	PRICE INT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE DIBS_DRAWER(
	CREATED_AT TIMESTAMP NULL DEFAULT NULL,
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES USER_INFO (ID),
	UNIQUE KEY UNIQUE_USER_DRAWER (USER_ID, NAME),
	KEY IDX_USER_ID(USER_ID)
);

CREATE TABLE DIBS(
	CREATED_AT TIMESTAMP NULL DEFAULT NULL,
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	DRAWER_ID BIGINT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) REFERENCES USER_INFO (ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
	FOREIGN KEY (DRAWER_ID) REFERENCES DIBS_DRAWER (ID),
	UNIQUE KEY UNIQUE_USER_DIBS (USER_ID, PRODUCT_ID),
	KEY IDX_USER_PRODUCT(USER_ID, PRODUCT_ID)
);



LOAD DATA INFILE '/docker-entrypoint-initdb.d/dummy_product.csv'
INTO TABLE PRODUCT
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;